---
server:
  addr: 0.0.0.0:9000
  path: /metrics

logs:
  level: error
  pretty: false

target:
  file: /etc/prometheus/scw.json
  refresh: 30
  credentials:
  - project: example1
    access_key:
    secret_key:
  - project: example2
    access_key:
    secret_key:
    zone: fr-par-1
  - project: example3
    access_key:
    secret_key:
    org:

...
