baseURL = "https://promhippie.github.io/prometheus-scw-sd/"
languageCode = "en-us"
title = "Prometheus Scaleway SD"
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Prometheus service discovery for Scaleway"
  keywords = "prometheus, sd, service, discovery, scaleway, scw"
