---
kind: Service
apiVersion: v1

metadata:
  name: prometheus-scw-sd
  labels:
    app.kubernetes.io/name: prometheus-scw-sd

spec:
  selector:
    app.kubernetes.io/name: prometheus-scw-sd

  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP

...
