---
name: kustomize

"on":
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Generate manifest
        id: kustomize
        uses: actionhippie/kustomize@v1
        with:
          version: 4.4.0
          path: deploy/kubernetes/
          target: deploy/kubernetes/bundle.yml

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: deploy/
          message: Automated kustomize update
          push: true
          commit: --signoff

...
